//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleConfiguration_Operations.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessForm()
        {
            this.PeriodPrices = new HashSet<PeriodPrice>();
            this.PriceModels = new HashSet<PriceModel>();
        }
    
        public int Id { get; set; }
        public int SalesConfigurationId { get; set; }
        public int RefCode { get; set; }
        public string WebText { get; set; }
        public string DescriptionText { get; set; }
    
        public virtual RefAccessForm RefAccessForm { get; set; }
        public virtual SalesConfiguration SalesConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodPrice> PeriodPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceModel> PriceModels { get; set; }
    }
}
