//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleConfiguration_Operations.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefPriceModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefPriceModel()
        {
            this.PriceModels = new HashSet<PriceModel>();
        }
    
        public int Code { get; set; }
        public string DisplayName { get; set; }
        public int RefAccessFormCode { get; set; }
        public string Text { get; set; }
        public bool ShowPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceModel> PriceModels { get; set; }
        public virtual RefAccessForm RefAccessForm { get; set; }
    }
}
