//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleConfiguration_Operations.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefPeriod
    {
        public int Id { get; set; }
        public int UnitValue { get; set; }
        public int RefPeriodUnitTypeCode { get; set; }
    
        public virtual RefPeriodUnitType RefPeriodUnitType { get; set; }
    }
}
