//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Jini.Utilities.TextCleanUp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesConfigurationHistory
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Value { get; set; }
        public string CreatedBy { get; set; }
        public int VersionNo { get; set; }
        public string Isbn { get; set; }
    }
}
