//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Gyldendal.Jini.SalesConfigurationServices.Models.Properties;

namespace Gyldendal.Jini.SalesConfigurationServices.Models
{
    

    public partial class DigitalProduct
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Isbn { get; set; }
        public string MediaTypeName { get; set; }
        public int MediaTypeId { get; set; }
        public string MaterialTypeName { get; set; }
        public int MaterialTypeId { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string DepartmentSectionName => $"{DepartmentName} - {SectionName}";
        public string MediaMaterialName => $"{MediaTypeName} - {MaterialTypeName}";
        public DateTime? PublishDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public List<DigitalProductAuthor> Authors { get; set; }
        public string AuthorsString => string.Join(", ", Authors.Select(a=>a.FullName));
        public int DepartmentId { get; set; }
        public int SectionId { get; set; }
        public bool HasConfiguration { get; set; }
        public bool HasDraft { get; set; }
        public string ConfigurationText { get; set; } = Settings.Default.InactiveConfiguration;
    }

    
}
