//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Jini.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductAccessProviders = new HashSet<ProductAccessProvider>();
        }
    
        public int Id { get; set; }
        public bool IsExternalLogin { get; set; }
        public string Isbn { get; set; }
        public string Title { get; set; }
        public string UnderTitle { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string GradeLevels { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> GpmMediaTypeId { get; set; }
        public Nullable<int> GpmMaterialTypeId { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string SectionCode { get; set; }
        public string SectionName { get; set; }
        public Nullable<Int64> ContainerInstanceId { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual MediaType MediaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAccessProvider> ProductAccessProviders { get; set; }
    }
}
