//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Jini.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialCount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrialCount()
        {
            this.TrialLicenses = new HashSet<TrialLicense>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UnitValue { get; set; }
        public int RefCountUnitTypeCode { get; set; }
    
        public virtual RefTrialCountUnitType RefTrialCountUnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrialLicense> TrialLicenses { get; set; }
    }
}
